name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install npm
          git clone https://github.com/nturley/netlistsvg.git
          cd netlistsvg
          sudo npm install -g . --legacy-peer-deps
      - name: Build
        run: |
          make
